# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: batch.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61tch.proto\"\x91\x01\n\x07Request\x12\r\n\x05rfwId\x18\x01 \x01(\t\x12\x15\n\rbenchmarkType\x18\x02 \x01(\t\x12\x11\n\tbatchType\x18\x03 \x01(\t\x12\x16\n\x0eworkloadMetric\x18\x04 \x01(\t\x12\x0f\n\x07\x62\x61tchId\x18\x05 \x01(\x05\x12\x11\n\tbatchUnit\x18\x06 \x01(\x05\x12\x11\n\tbatchSize\x18\x07 \x01(\x05\"\xd7\x01\n\x08Response\x12\r\n\x05rfwId\x18\x01 \x01(\t\x12\x13\n\x0blastBatchId\x18\x02 \x01(\x05\x12\x17\n\x07\x62\x61tches\x18\x03 \x03(\x0b\x32\x06.Batch\x12\x0f\n\x07maximum\x18\x04 \x01(\x05\x12\x0f\n\x07minimum\x18\x05 \x01(\x05\x12\x0f\n\x07\x61verage\x18\x06 \x01(\x02\x12\x13\n\x0bstDeviation\x18\x07 \x01(\x02\x12\x0c\n\x04tenP\x18\x08 \x01(\x02\x12\x0e\n\x06\x66iftyP\x18\t \x01(\x02\x12\x13\n\x0bninetyFiveP\x18\n \x01(\x02\x12\x13\n\x0bninetyNineP\x18\x0b \x01(\x02\"\x18\n\x05\x42\x61tch\x12\x0f\n\x07samples\x18\x01 \x03(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'batch_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=16
  _REQUEST._serialized_end=161
  _RESPONSE._serialized_start=164
  _RESPONSE._serialized_end=379
  _BATCH._serialized_start=381
  _BATCH._serialized_end=405
# @@protoc_insertion_point(module_scope)
